//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostsID { get; set; }
        public string Post1 { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
